### ISSUE TITLE
when I run start.py, but tail-database-api get a error

### ISSUE THREAD

**Issue by LCG22** [Tail-Database/tail-database-exporter#1]
error info:

[Nest] 189241  - 01/03/2023, 9:55:13 PM   ERROR [ExceptionsHandler] connect ECONNREFUSED 127.0.0.1:8562
Error: connect ECONNREFUSED 127.0.0.1:8562
    at Function.AxiosError.from (tail-database-api/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (tail-database-api/node_modules/axios/lib/adapters/http.js:526:25)
    at RedirectableRequest.emit (node:events:527:28)
    at ClientRequest.eventHandlers.<computed> (tail-database-api/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

how can I do ?

**Comment by LCG22** [comment]
When I run 'chia start data', I solved the problem, But I have a empty array( [ ] ).

So, How to I do ?

**Comment by LCG22** [comment]
when I run :
chia data create_data_store
chia data subscribe -store fd1078bf0d01743e8e685b72635ca15488f5adce0da016b229f8885a3de36c0f

I solved the problem When I wait for some time.

You can see the blog:
https://blog.csdn.net/Sbtgmz/article/details/128571727
